### ISSUE TITLE
setup-rack.sh failure with RACK-v13.0 and Python 3.8.10 on Ubuntu 20.04

### ISSUE THREAD

**Issue by GregIthaca** [ge-high-assurance/RACK#1029]
I attempted to upgrade from RACK-v12.0 to RACK-v13.0, but ran into a problem while executing the `setup-rack.sh` script. I believe this is a new issue as of this version. The `BooleanOptionalAction` for `argparse` was newly introduced into Python 3.9, and thus does not work in Python 3.8.10, which I believe is the current default version for Ubuntu 20.04.

I must have missed any specific notification that a later Python version was required. It's probably useful at least to not that, following the tutorial steps, this is probably the first place that the compatibility issue will show up for a user.

```
$ ./setup-rack.sh
Traceback (most recent call last):
  File "/home/gnelson/venv/RACK-v13.0/bin/rack", line 8, in <module>
    sys.exit(main())
  File "/home/gnelson/venv/RACK-v13.0/lib/python3.8/site-packages/rack/rack_cmd.py", line 48, in main
    args = get_argument_parser().parse_args()
  File "/home/gnelson/venv/RACK-v13.0/lib/python3.8/site-packages/rack/__init__.py", line 970, in get_argument_parser
    manifest_import_parser.add_argument('--optimize', default=True, action=argparse.BooleanOptionalAction, help='Enable RACK UI optimization when available')
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
```

**Comment by glguy** [comment]
We do all of our testing on the current Ubuntu LTS release. The rack CLI commands are also available inside the RACK docker image via `docker exec`. Support outside of that version of Ubuntu is accidental.
